on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm install -D
      - name: Build extension
        run: npx web-ext build -s 'src' -a 'out'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-extension
          path: out/*
